### Find all content
GET http://localhost:8085/api/content


### Create a new content
POST http://localhost:8085/api/content
Content-Type: application/json

{
    "title": "My second Blog post",
    "description": "second blog",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2024-01-31T19:14:29.888679",
    "dateUpdated": null,
    "url": ""
  }

### Get content by id
GET http://localhost:8085/api/content/2

### Update existing content
PUT http://localhost:8085/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MY First POST",
  "description": "MY First POST!!!",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-01-31T19:14:29.888679",
  "dateUpdated": "2024-01-31T19:14:29.888679",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Delete existing content
DELETE http://localhost:8085/api/content/1
